spring.application.name=student-portal-backend

# ---- DataSource ----
spring.datasource.url=jdbc:mariadb://localhost:3306/student_portal
spring.datasource.username=root
spring.datasource.password=root

# ---- JPA / Hibernate ----
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

server.port=8081